name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'deltarobotone/visy_neopixel_pkg/workflows@master'
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
