name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: deltarobotone/visy_neopixel_pkg
          path: visy_neopixel_pkg
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
