name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Clone visy_neopixel_package
        run: cd /root/src && git clone https://github.com/deltarobotone/visy_neopixel_pkg.git
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
